### PR TITLE
Remove mention of media-folder from README.md

### PR DESCRIPTION
**Pull request by saarasat**
Mention of media-folder is removed from `README.md` as it is not being used for any permanent data storage.

# Testing

All existing unit- and selenium-tests pass

# Have you updated the README or other relevant documentation?

This will make README to be up-to-date

# Is it [Done](https://wiki.aalto.fi/display/EDIT/Definition+of+Done)?

- [ ] I (developer) have created unit tests and the tests pass
- [ ] I (developer) have created functional tests (Selenium tests) if applicable
- [x] I (developer) have tested the changes manually
- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

### CODE REVIEW

**Comment by raphendyr** [comment]
Is this the problematic test? https://github.com/apluslms/a-plus/blob/master/exercise/tests.py#L741

**Comment by saarasat** [comment]
> Is this the problematic test? https://github.com/apluslms/a-plus/blob/master/exercise/tests.py#L741

Yes

**Comment by raphendyr** [comment]
I think the problem is with some write permissions. I think a better solution would be using virtual buffers for the files, instead of writing them to the disk. For that, there is https://docs.python.org/3/library/io.html

```python
file_a = io.BytesIO(b'\x00\x00') # the png data
file_b = io.StringIO("Tekijät ja Hyyppö")

                response = self.client.post(exercise.get_absolute_url(), {
                    "key": "value",
                    "file1": file_a,
                    "file2": file_b,
                })
```

**Comment by raphendyr** [comment]
I replaced the filesystem stuff with virtual buffers in 090ca115df62075a2327160d0d135428ad3db565, which might fix the problem for you. Can you verify that the problem is fixed by it?

**Comment by saarasat** [comment]
> I replaced the filesystem stuff with virtual buffers in [090ca11](https://github.com/apluslms/a-plus/commit/090ca115df62075a2327160d0d135428ad3db565), which might fix the problem for you. Can you verify that the problem is fixed by it?

Yes, the problem was fixed, great! However, there is now the empty, broken link in README.md,  should that be removed? or at least the link removed, even if the mention of the folder remains?

**Comment by raphendyr** [comment]
It would be a good idea to remove `media/` from the README as the data is not stored there in containers or in production.

**Comment by saarasat** [comment]
> It would be a good idea to remove `media/` from the README as the data is not stored there in containers or in production.

Did that and updated the commit message of this very very short PR.

**Pull request merged**
