### PR TITLE
Introduce xAPI support

### PR DESCRIPTION
**Pull request by teemulehtinen**
Extends hook implementation to support xAPI protocol which can record events in an external learning data warehouse, LRS. - a master's thesis contribution

### CODE REVIEW

**Comment by Plustest** [comment]
Build finished.

**Comment by Plustest** [comment]
Build finished.

**Comment by teemulehtinen** [comment]
retest this please

**Comment by teemulehtinen** [comment]
retest this please

**Comment by teemulehtinen** [comment]
This introduces some overhead so I recommend to not merge until there is a use case to build and improve in practice.

**Comment by PasiSa** [comment]
Closing with Teemu's permission.

**Pull request closed without merging**
