### PR TITLE
Type hinting for mixins

### PR DESCRIPTION
**Pull request by skulonen**
# Description

**What?**

This PR adds type hinting to all mixin classes.

**Why?**

The team decided to start using type hints, and adding them to mixins facilitates adding them to other places, since many classes depend on mixins.

**How?**

The following things have been done:
- Create base classes that declare methods that the mixins use through `self` or `super()`. The base classes are replaced with an empty class at runtime, so that the method declarations don't appear in the MROs of the mixin classes. As such, they exist solely for type checking purposes. They're defined in `authorization/types.py`, `course/types.py` and `exercise/types.py` (depending on which classes they use) or `lib/types.py` (when they only use Python builtin/Django/DRF classes), and are named "Supports*".
- Add type hints to method parameters and return values.
- Remove unused imports.
- `cast` was needed in two situations: when getting a LearningObject from an arbitrary dict (`edit_course/exercise_forms.py`) and when using getattr (`lib/api/mixins.py`).

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [x] Django unit tests.
- [x] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Tested manually that the main site and API work.

**Did you test the changes in**

- [ ] Chrome
- [x] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

### CODE REVIEW

**Comment by lainets** [comment]
I thought the point was to directly inherit from the appropriate classes unless there were multiple options like AuthorizationMixin/APIView... The other problem is that if every method has its own Supports* class, you get zero information out of it, might as well do `# type: ignore`. I had thought we would make a single class that represents AuthorizationMixin and APIView, this would give the programmer the contextual information that this class should have one of these as a super class.

From my opinion type hints have two purposes: (1) check the correctness of the code and (2) give the programmer information about types. The reason why I think Supports* should only be used when needed is that it effectively says "ignore type errors for these methods" i.e. we lose the first purpose. The second purpose is also lost if in addition every method has it's own class (or you could add a comment saying what usually implements the method in question, but I think it would make more sense to have the Supports* classes represent actual classes, though you will most likely need the comment in this case too)

**Comment by lainets** [comment]
Note that the Supports* works fine when used as Protocols on function parameters because then the linter can check that the methods exist. This just doesn't work when typing super classes.

**Comment by skulonen** [comment]
Okay, seems like there was a misunderstanding between us at some point and I got the impression that you preferred these Supports* classes in general, and I just went along with it because the consistency appealed to me. But you're right that we lose all static guarantees when we do this. Well, no big deal, I'll get back to this in a while.

**Review by Mankro — COMMENTED** [review]
Should this PR be closed without merging? We don't want to continue with a dozen SupportsMethod classes for static typing.

**Comment by Mankro** [comment]
> Should this PR be closed without merging? We don't want to continue with a dozen SupportsMethod classes for static typing.

Closing now.

**Pull request closed without merging**
