### PR TITLE
Optimize course configuring

### PR DESCRIPTION
**Pull request by lainets**
# Description

**What?**

Optimizes database access in course configuring.
Adds simple unit tests to test the course structure after configure call.

**Why?**

Course configuring has been extremely slow.

**How?**

By fetching objects in a single query and only updating objects that have changes.

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [X] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [ ] Manual testing.

**Did you test the changes in**

- [ ] Chrome
- [ ] Firefox
- [X] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [X] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [X] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [X] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

### CODE REVIEW

**Comment by lainets** [comment]
This should close #1078. While there still are improvement possibilities, I do not think they are necessary or worth the effort.

**Review by Mankro — CHANGES_REQUESTED** [review]
Great, this looks good! I have some questions and very minor changes.

* I don't understand all parts of the code well, e.g., comparing the new and old configs and using the difference in updating the database. We could discuss them in the office so that I get the big picture.
* If the teacher changes the type of an exercise to another, then is the A+ database updated correctly? E.g., if an LTIExercise with some key turns into a BaseExercise using the same key in the new version of the course configs (aplus-json).
* I assume this works like it used to be: if the new aplus-json from the course git repo does not define some exercise keys that used to be in the course, then does the A+ front delete those exercises from the database assuming that there are no submissions attached to them?
* If the aplus-json config used to define some setting with a non-default value, and then the teacher wants to reset it to the default by removing the whole setting from the course git repo, then does the A+ front update the setting or is it stuck in the old value? This tends to be a problem since our code changes values in the database only when the setting is defined in the new downloaded configurations. (All the `if key in o:` statements.)

**Comment by lainets** [comment]
> If the teacher changes the type of an exercise to another, then is the A+ database updated correctly? E.g., if an LTIExercise with some key turns into a BaseExercise using the same key in the new version of the course configs (aplus-json).

Yes.

> I assume this works like it used to be: if the new aplus-json from the course git repo does not define some exercise keys that used to be in the course, then does the A+ front delete those exercises from the database assuming that there are no submissions attached to them?

Yes, the behaviour should be the same.

> If the aplus-json config used to define some setting with a non-default value, and then the teacher wants to reset it to the default by removing the whole setting from the course git repo, then does the A+ front update the setting or is it stuck in the old value? This tends to be a problem since our code changes values in the database only when the setting is defined in the new downloaded configurations. (All the `if key in o:` statements.)

I tried to keep the behaviour the same as before, so this is still a problem. Fixing this requires adding some kind of 'deleted' flag to the diff for missing fields (e.g. set the field equal to a custom singleton `Deleted`), and then resetting the fields to default if the flag is present.

**Review by Mankro — APPROVED** [review]
Excellent!

**Pull request merged**
